apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: gslb
spec:
  ingress:
    ingressClassName: nginx
    rules:
      - host: demo.cloud.example.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                  name: frontend-podinfo
                  port:
                    name: http
  strategy:
    type: roundRobin
    splitBrainThresholdSeconds: 300
    dnsTtlSeconds: 15
    weight:
      eu: 1 # test-gslb1
      us: 3 # test-gslb3
